apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nautilus
  labels:
    app: frontend
spec:
  capacity:
     storage: 400M
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/dba
    
 
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nautilus
  labels:
     app: frontend
spec:
  accessModes:
  - ReadWriteOnce
  volumeName: pv-nautilus
  resources:
     requests:
        storage: 200M
  storageClassName: manual
 

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nautilus
  labels: 
    app: frontend
spec:
    containers:
    - image: httpd:latest
      name: container-nautilus
      ports:
      - containerPort: 80 
        name: web
      volumeMounts:
      - name: storage-nautilus
        mountPath: /var/www/html

    volumes:
    - name: storage-nautilus
      persistentVolumeClaim:
          claimName: pvc-nautilus
          
          
          
---
apiVersion: v1
kind: Service
metadata: 
  name: web-nautilus
spec: 
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    nodePort: 30008
  selector: 
     app: frontend
     

